# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pf5Bhy7SyxF_LdBfyhAp3CXgbaYW-Di6
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.cluster import KMeans
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

st.set_page_config(page_title="Ad Profit AI", layout="wide")
st.title("Ad Profit AI – Instant Ad Money Leak Detector")
st.markdown("**Google + LinkedIn + Meta Ads → One-click profit insights**")

# File uploader (works even without your original files)
uploaded_files = st.file_uploader("Upload your ad CSV files (optional)", type=["csv"], accept_multiple_files=True)

if uploaded_files and len(uploaded_files) >= 1:
    dfs = [pd.read_csv(f) for f in uploaded_files]
    google = linkedin = meta = dfs[0]  # fallback
    for f, df in zip(uploaded_files, dfs):
        name = f.name.lower()
        if 'google' in name: google = df
        elif 'linkedin' in name or 'linked' in name: linkedin = df
        else: meta = df
else:
    st.info("Using demo data — upload your own files to analyze!")
    # Replace these paths with your actual raw file names in repo
    try:
        google = pd.read_csv("google_ads-sheet1-sourcetable.csv")
        linkedin = pd.read_csv("linked_in_campaigns-sheet1-sourcetable.csv")
        meta = pd.read_csv("meta_ads_campigns-sheet1-sourcetable.csv")
    except:
        st.error("Please upload your CSV files or fix file names")
        st.stop()

# Clean & unify
def unify(g, l, m):
    g['Cost'] = g['Cost'].astype(str).str.replace(r'[$,]', '', regex=True).astype(float)
    l['Total Spent (USD)'] = l['Total Spent (USD)'].astype(str).str.replace(r'[$,]', '', regex=True).astype(float)
    m['Amount spent'] = m['Amount spent'].astype(str).str.replace(r'[$,]', '', regex=True).astype(float)
    if 'Purchase value' in m.columns:
        m['Purchase value'] = m['Purchase value'].astype(str).str.replace(r'[$,]', '', regex=True).astype(float)

    g = g.rename(columns={'Day':'Date','Campaign':'Campaign Name','Country':'Region','Cost':'Spend'})
    g['Platform'] = 'Google Ads'; g['Revenue'] = 0

    l = l.rename(columns={'Day':'Date','Total Spent (USD)':'Spend'})
    if 'Conversions' in l.columns: l.drop(columns=['Conversions'], inplace=True)
    l = l.rename(columns={'Leads':'Conversions'})
    l['Platform'] = 'LinkedIn'; l['Revenue'] = 0; l['Region'] = 'Global'

    m = m.rename(columns={'Campaign name':'Campaign Name','Amount spent':'Spend','Purchases':'Conversions','Purchase value':'Revenue'})
    m['Platform'] = 'Meta'; m['Region'] = 'Unknown'

    cols = ['Date','Platform','Campaign Name','Region','Impressions','Clicks','Spend','Conversions','Revenue']
    g = g.reindex(columns=cols, fill_value=0)
    l = l.reindex(columns=cols, fill_value=0)
    m = m.reindex(columns=cols, fill_value=0)

    df = pd.concat([g, l, m], ignore_index=True)
    df['ROAS'] = (df['Revenue']/df['Spend']).replace([np.inf, -np.inf], 0).fillna(0)
    return df

df = unify(google, linkedin, meta)

# ML
X = df[['Spend','Conversions','Revenue','ROAS']].fillna(0)
X_scaled = StandardScaler().fit_transform(X)
df['Segment'] = KMeans(n_clusters=4, random_state=42, n_init=10).fit_predict(X_scaled)

# Dashboard
c1, c2, c3, c4 = st.columns(4)
c1.metric("Total Spend", f"${df['Spend'].sum():,.0f}")
c2.metric("Revenue", f"${df['Revenue'].sum():,.0f}")
c3.metric("Profit", f"${df['Revenue'].sum() - df['Spend'].sum():,.0f}")
c4.metric("ROAS", f"{df['ROAS'].mean():.2f}x")

bleeding = df[(df['Spend']>200) & (df['Conversions']==0) & (df['Revenue']==0)]
if len(bleeding)>0:
    st.error(f"PAUSE THESE {len(bleeding)} CAMPAIGNS → ${bleeding['Spend'].sum():,.0f} WASTED!")

fig = px.scatter(df, x="Spend", y="Revenue", color="Platform", size="ROAS", hover_data=["Campaign Name"],
                 title="Where Your Ad Money Actually Makes Profit")
st.plotly_chart(fig, use_container_width=True)

st.success("Deployed successfully! Ready for clients!")
st.balloons()