# -*- coding: utf-8 -*-
"""Untitled92.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M99V-rXz5L_jMVEPJFTCuNpuUrH5H8S0
"""

!pip install streamlit
!pip install plotly
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

st.set_page_config(page_title="Ad Profit AI", layout="wide")
st.title("Ad Profit AI")

uploaded_files = st.file_uploader(
    "Upload your Google Ads, LinkedIn, and Meta CSV files",
    type=["csv"],
    accept_multiple_files=True
)

if not uploaded_files:
    st.info("Please upload at least one CSV file to analyze your ad data.")
    st.stop()

# Process uploaded files
dfs = []
for uploaded_file in uploaded_files:
    df = pd.read_csv(uploaded_file)
    dfs.append(df)

if not dfs:
    st.error("No valid files were uploaded.")
    st.stop()

# Combine all uploaded files into one dataframe and continue with calculations
# Only proceed if dfs is not empty to avoid ValueError
if dfs:
    df = pd.concat(dfs, ignore_index=True)

    # Continue with your data processing, calculations, and visualization code here
    # ...

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Total Spend", f"${df['Spend'].sum():,.0f}")
    col2.metric("Revenue", f"${df['Revenue'].sum():,.0f}")
    col3.metric("Profit", f"${df['Revenue'].sum() - df['Spend'].sum():,.0f}")
    col4.metric("ROAS", f"{df['ROAS'].mean():.2f}x")